In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [11]:
np.zeros(5) # 1-D Array 

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5 , dtype= int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2,2)) # 2-D array

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((2,2) , dtype= int)

array([[0, 0],
       [0, 0]])

In [15]:
np.zeros((5,10) , dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
 np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,3) , dtype = int )

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.fours(2)

In [19]:
random.rand(4)

NameError: name 'random' is not defined

In [20]:
np.random.rand(4)

array([0.40640579, 0.78658602, 0.53281623, 0.1320836 ])

In [21]:
np.random.rand(4)

array([2.95976582e-01, 1.52325300e-04, 9.77524935e-01, 6.13030119e-01])

In [22]:
np.random.rand(4)

array([0.75773254, 0.13871899, 0.4259569 , 0.9500766 ])

In [23]:
np.random.rand(4 , 5)

array([[0.99867012, 0.42466402, 0.91519069, 0.60276739, 0.77470164],
       [0.66001212, 0.27882922, 0.4175755 , 0.00699147, 0.37066325],
       [0.86706633, 0.80414989, 0.32175372, 0.60798248, 0.73220992],
       [0.89142142, 0.94051131, 0.70959791, 0.58140868, 0.5250968 ]])

In [24]:
np.random.rand(2,2)

array([[0.20677366, 0.07917744],
       [0.06351671, 0.76959548]])

In [25]:
np.random.randint(3)

0

In [26]:
np.random.randint(10,20)

17

In [27]:
np.random.randint(1,5,3)

array([3, 3, 3], dtype=int32)

In [28]:
np.random.randint(1,5,4)

array([4, 1, 4, 4], dtype=int32)

In [29]:
np.random.randint(5,2,3)

ValueError: low >= high

In [30]:
np.random.randint(-5,2,3)

array([-1,  1, -2], dtype=int32)

In [31]:
np.random.randint(10,40,(10,10)) # 10 * 10 matrix with value between 10 - 40

array([[12, 30, 26, 39, 29, 31, 24, 14, 24, 19],
       [18, 29, 26, 31, 36, 23, 37, 10, 11, 16],
       [14, 13, 31, 27, 39, 29, 22, 28, 11, 37],
       [25, 21, 27, 16, 10, 37, 32, 34, 11, 23],
       [31, 36, 29, 19, 26, 39, 37, 30, 38, 19],
       [15, 10, 20, 21, 19, 21, 30, 29, 10, 15],
       [35, 28, 36, 30, 39, 32, 32, 20, 27, 17],
       [32, 10, 32, 38, 13, 30, 38, 25, 30, 25],
       [33, 38, 30, 16, 37, 14, 27, 19, 38, 24],
       [26, 19, 19, 37, 33, 18, 27, 15, 19, 13]], dtype=int32)

In [32]:
ri = np.random.randint(10,40,(10,10)) 
ri

array([[17, 29, 31, 16, 15, 27, 20, 24, 16, 27],
       [27, 33, 26, 15, 24, 18, 29, 27, 13, 11],
       [32, 24, 26, 26, 35, 35, 37, 39, 14, 33],
       [18, 39, 23, 25, 36, 16, 15, 19, 31, 11],
       [34, 19, 24, 39, 27, 33, 26, 29, 37, 36],
       [10, 38, 13, 19, 34, 16, 13, 20, 11, 29],
       [11, 18, 29, 22, 34, 11, 11, 16, 13, 37],
       [37, 17, 13, 23, 12, 12, 20, 19, 31, 13],
       [20, 28, 16, 13, 14, 11, 29, 38, 10, 20],
       [22, 19, 18, 10, 15, 20, 15, 27, 13, 29]], dtype=int32)

In [33]:
len(ri)  # it will print bydefault rows

10

In [34]:
ri = np.random.randint(10,40,(3,5)) 
ri

array([[38, 25, 10, 27, 21],
       [11, 18, 39, 35, 19],
       [36, 34, 13, 35, 11]], dtype=int32)

In [35]:
len(ri)

3

In [36]:
ri.shape # it will give rows and column

(3, 5)

In [37]:
id(ri)

2273040158512

In [38]:
ri

array([[38, 25, 10, 27, 21],
       [11, 18, 39, 35, 19],
       [36, 34, 13, 35, 11]], dtype=int32)

# Slicing of NumPy

In [39]:
ri[:]

array([[38, 25, 10, 27, 21],
       [11, 18, 39, 35, 19],
       [36, 34, 13, 35, 11]], dtype=int32)

In [40]:
ri[1]

array([11, 18, 39, 35, 19], dtype=int32)

In [41]:
ri[0:3]

array([[38, 25, 10, 27, 21],
       [11, 18, 39, 35, 19],
       [36, 34, 13, 35, 11]], dtype=int32)

In [42]:
ri_1 = np.random.randint(10,40,(10,10)) 
ri_1

array([[33, 27, 33, 31, 25, 29, 35, 34, 37, 19],
       [11, 34, 13, 31, 35, 14, 25, 39, 33, 15],
       [18, 15, 22, 32, 33, 22, 18, 26, 29, 39],
       [31, 16, 10, 39, 15, 19, 27, 13, 30, 27],
       [23, 26, 29, 22, 22, 11, 34, 15, 38, 31],
       [22, 39, 34, 13, 28, 19, 23, 14, 19, 10],
       [33, 26, 15, 33, 23, 20, 38, 32, 39, 18],
       [24, 11, 11, 16, 12, 36, 38, 29, 12, 39],
       [10, 25, 12, 24, 33, 21, 23, 20, 21, 33],
       [20, 35, 20, 12, 32, 10, 28, 36, 33, 17]], dtype=int32)

In [43]:
ri_1.shape

(10, 10)

In [44]:
ri_1 = np.random.randint(10,40,(10,10)) 
print(ri_1)

[[14 24 37 39 18 10 25 13 10 21]
 [34 11 33 25 39 19 32 23 21 28]
 [12 12 21 12 31 10 33 33 11 24]
 [35 31 36 34 25 28 15 38 16 36]
 [11 14 21 17 35 36 26 29 14 27]
 [39 29 12 19 20 24 10 27 19 25]
 [22 14 12 19 32 22 20 12 29 13]
 [26 31 20 32 24 26 19 37 18 34]
 [18 24 37 26 37 11 22 26 30 37]
 [18 22 29 19 14 31 36 37 18 21]]


In [45]:
ri_1

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [46]:
ri_1[:]

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [47]:
ri_1[3:8]

array([[35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34]], dtype=int32)

In [48]:
print(ri_1[3,8])

16


In [49]:
ri_1

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [50]:
ri_1[-5]

array([39, 29, 12, 19, 20, 24, 10, 27, 19, 25], dtype=int32)

In [51]:
print(ri_1[-5,-3])

27


In [52]:
ri_1

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [53]:
ri_1[::3]

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [54]:
ri_1[::-1]

array([[18, 22, 29, 19, 14, 31, 36, 37, 18, 21],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [14, 24, 37, 39, 18, 10, 25, 13, 10, 21]], dtype=int32)

In [55]:
ri_1[::-5]

array([[18, 22, 29, 19, 14, 31, 36, 37, 18, 21],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27]], dtype=int32)

In [56]:
print(ri_1[2])      # get speccific row
print(ri_1[:, 2])   # get specific column
      

[12 12 21 12 31 10 33 33 11 24]
[37 33 21 36 21 12 12 20 37 29]


In [57]:
ri_1

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [58]:
print(ri_1[:, 8])

[10 21 11 16 14 19 29 18 30 18]


In [59]:
print(ri_1[:, -8])

[37 33 21 36 21 12 12 20 37 29]


In [60]:
ri_1

array([[14, 24, 37, 39, 18, 10, 25, 13, 10, 21],
       [34, 11, 33, 25, 39, 19, 32, 23, 21, 28],
       [12, 12, 21, 12, 31, 10, 33, 33, 11, 24],
       [35, 31, 36, 34, 25, 28, 15, 38, 16, 36],
       [11, 14, 21, 17, 35, 36, 26, 29, 14, 27],
       [39, 29, 12, 19, 20, 24, 10, 27, 19, 25],
       [22, 14, 12, 19, 32, 22, 20, 12, 29, 13],
       [26, 31, 20, 32, 24, 26, 19, 37, 18, 34],
       [18, 24, 37, 26, 37, 11, 22, 26, 30, 37],
       [18, 22, 29, 19, 14, 31, 36, 37, 18, 21]], dtype=int32)

In [61]:
print(ri_1[0:3 , 0:3])

[[14 24 37]
 [34 11 33]
 [12 12 21]]


In [62]:
print(ri_1[5:8 , 0:3])

[[39 29 12]
 [22 14 12]
 [26 31 20]]


In [63]:
print(ri_1[: , 2:3])

[[37]
 [33]
 [21]
 [36]
 [21]
 [12]
 [12]
 [20]
 [37]
 [29]]


In [64]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [67]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# NumPy Masking or filter

In [69]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [70]:
id(mat)

2273040315280

In [71]:
mat.shape

(10, 10)

In [72]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [73]:
print(mat[mat < 50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [74]:
print(mat[mat <= 50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [75]:
print(mat[mat == 50])

[50]


In [76]:
print(mat[mat != 50])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [77]:
print(mat[mat > 50])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


# Without work in import* find the median , method

In [79]:
arr

array([0, 1, 2, 3, 4, 5])

In [80]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [81]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [82]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [84]:
arr.reshape(2,3,order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
arr.reshape(2,3,order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [86]:
arr.reshape(2,3,order = 'A')

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
arr

array([0, 1, 2, 3, 4, 5])

In [88]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [89]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [91]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
row = 4
col = 5

In [93]:
row

4

In [94]:
col

5

In [95]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
print(mat[row,col])

45


In [98]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
col = 6

In [101]:
mat[6]  # bydefault it represent the row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [103]:
print(mat[:,6])

[ 6 16 26 36 46 56 66 76 86 96]


In [108]:
print(mat[row,:])

[40 41 42 43 44 45 46 47 48 49]


In [109]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [110]:
print(mat[:,8])

[ 8 18 28 38 48 58 68 78 88 98]


In [114]:
mat[:col]  # bydefault it also takes rows here

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [115]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [116]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [118]:
mat[1,4]

np.int64(14)

In [119]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [126]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [128]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [129]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

# dt - 27-03-2026

# 1 - Array creation Functionality

In [2]:
import numpy as np

In [3]:
b = np.arange(0,10,2)
print('Array b:', b)

Array b: [0 2 4 6 8]


In [4]:
#create an array filled with zeros
d = np.zeros((2,3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# create array filled with one
e = np.ones((3,2))
print("Array e :\n" , e)

Array e :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
# create identity matrix
f = np.eye(4)
print("Identity matrix f : \n" ,f)

Identity matrix f : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2 - Array manupilation function

In [7]:
# reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3))
print('Reahaped array:' , reshaped)

Reahaped array: [[1 2 3]]


In [8]:
# reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1))
print('Reahaped array:' , reshaped)

Reahaped array: [[1]
 [2]
 [3]]


In [9]:
# faltten array
f1 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattened = np.ravel(f1)
print('falltened array:',flattened)

falltened array: [1 2 3 4 5 6 7 8]


In [10]:
#transpose the array
e1= np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Trasposed array :\n" ,transposed)

Trasposed array :
 [[1 3]
 [2 4]]


In [11]:
# starck arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print('Stacked array:\n',stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [12]:
# starck arrays horizontically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print('Stacked array:\n',stacked)

Stacked array:
 [1 2 3 4]


# 3 - Mathematical Function

In [13]:
# add 2 arrays
g = np.array([1,2,3,4])
added = np.add(g,2)
print('Added 2 to g:',added)

Added 2 to g: [3 4 5 6]


In [14]:
#square each element
squared = np.power(g,2)
print('squared g:' , squared)

squared g: [ 1  4  9 16]


In [15]:
#square-root of each element
sqrt_val = np.sqrt(g)
print('square root :',sqrt_val)

square root : [1.         1.41421356 1.73205081 2.        ]


In [16]:
a1 = [1,2,3]

In [17]:
g = [1,2,3,4]

In [18]:
print(a1)
print(g)

[1, 2, 3]
[1, 2, 3, 4]


In [22]:
#dot product of array
a2 = np.array([1,2,3])
dot_product = np.dot(a1,g)
print('Dot product :' , dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [23]:
a = [1,2,3]
a

[1, 2, 3]

In [24]:
print(a)
print(a1)

[1, 2, 3]
[1, 2, 3]


In [26]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,a1)
print('Dot product of a & a1 : ',dot_product)

Dot product of a & a1 :  14


# 4 - Statistical Functions

In [29]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print('Mean of S :' , mean)   # find the average 

Mean of S : 2.5


In [34]:
# variance of array
s = np.array([1,2,3,4])
var = np.var(s)
print('Variance of S : ' , var)

Variance of S :  1.25


In [35]:
# standard deviation of array
s = np.array([1,2,3,4])
std_dev = np.std(s)
print('Standard Deviation of s :' , std_dev)

Standard Deviation of s : 1.118033988749895


In [37]:
# Minimum element of array
s = np.array([1,2,3,4])
minimum = np.min(s)
print('Minimun :' , minimum)

Minimun : 1


In [39]:
# Maximum element of array
s = np.array([1,2,3,4])
maximum = np.max(s)
print('Maximun :' , maximum)

Maximun : 4


# 5 - Linear algebra

In [40]:
# create a matrix
matrix = np.array([[1,2],[3,4]])
print('matrix:', matrix)

matrix: [[1 2]
 [3 4]]


# 6 - Random samplig function

In [42]:
# generate random value between 0 and 1
random_vals = np.random.rand(3)
print('random value :',random_vals)

random value : [0.49137374 0.74968886 0.63092682]


In [43]:
# set seed for reproducibility
np.random.seed(0)

# generate random value between 0 and 1
random_vals = np.random.rand(3)
print('random value :',random_vals)

random value : [0.5488135  0.71518937 0.60276338]


In [46]:
# genarate random integers
rand_ints = np.random.randint(1,10,size = 5)
print('random integer :' , rand_ints)

random integer : [4 6 3 5 8]


In [47]:
np.random.seed(0)

# genarate random integers
rand_ints = np.random.randint(1,10,size = 5)
print('random integer :' , rand_ints)

random integer : [6 1 4 4 8]


# Boolean & Logical Function

In [54]:
# check if all elements are true
# All
logical_test = np.array([False,True,True])
all_true = np.all(logical_test) # check if all elemmts are true
print('All elements are true :' , all_true)

All elements are true : False


In [55]:
# check if all elements are true

logical_test = np.array([False,True,False])
all_true = np.all(logical_test) # check if all elemmts are true
print('All elements are true :' , all_true)

All elements are true : False


In [59]:
# check if all elements are true

logical_test = np.array([True,True,False])
all_true = np.all(logical_test) # check if all elemmts are true
print('All elements are true :' , all_true)

All elements are true : False


In [60]:
#any
any_true = np.any(logical_test)
print('any elements are true :',any_true)

any elements are true : True


In [62]:
logical_test = np.array([False,False,False])
any_true = np.any(logical_test)
print('any elements are true :',any_true)

any elements are true : False


# Set operations

In [63]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [64]:
#Union 
union = np.union1d(set_a , set_b)
print('Union of a and b :' , union)

Union of a and b : [1 2 3 4 5 6]


# Array Atribute Function

In [65]:
# array attribute
a = np.array([1,2,3])
shape = a.shape # Shape of array
size = a.size # number of elements
dimensions = a.ndim # number of dimenstion
dtype = a.dtype # Data type of array

print('Shape of array :' , shape)
print('Size of array:' , size)
print('Dimentions of array:',dimensions)
print('datatype of array : ' , dtype)

Shape of array : (3,)
Size of array: 3
Dimentions of array: 1
datatype of array :  int64


# Other function

In [66]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [67]:
# size in bytes of array
array_size_in_bytess = a.nbytes
print('Size of array in bytes :' , array_size_in_bytess)

Size of array in bytes : 24


In [68]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
